>> anaconda-3-5.3.1 has been loaded.
>> python-3.8.2 has been loaded.
>> cuda-10.1_cudnn-7.6.5 has been loaded.
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /home/arlan.uy/.local/include/python3.7m/UNKNOWN
sysconfig: /home/arlan.uy/.local/include/python3.7/UNKNOWN
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /home/arlan.uy/.local/include/python3.7m/UNKNOWN
sysconfig: /home/arlan.uy/.local/include/python3.7/UNKNOWN
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /home/arlan.uy/.local/include/python3.7m/UNKNOWN
sysconfig: /home/arlan.uy/.local/include/python3.7/UNKNOWN
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /home/arlan.uy/.local/include/python3.7m/UNKNOWN
sysconfig: /home/arlan.uy/.local/include/python3.7/UNKNOWN
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /home/arlan.uy/.local/include/python3.7m/UNKNOWN
sysconfig: /home/arlan.uy/.local/include/python3.7/UNKNOWN
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /home/arlan.uy/.local/include/python3.7m/UNKNOWN
sysconfig: /home/arlan.uy/.local/include/python3.7/UNKNOWN
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /home/arlan.uy/.local/include/python3.7m/UNKNOWN
sysconfig: /home/arlan.uy/.local/include/python3.7/UNKNOWN
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /home/arlan.uy/.local/include/python3.7m/UNKNOWN
sysconfig: /home/arlan.uy/.local/include/python3.7/UNKNOWN
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
Traceback (most recent call last):
  File "/opt/hpcc/CPU/anaconda/3-5.3.1/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/hpcc/CPU/anaconda/3-5.3.1/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/arlan.uy/.local/lib/python3.7/site-packages/pip/__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "/home/arlan.uy/.local/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/arlan.uy/.local/lib/python3.7/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/arlan.uy/.local/lib/python3.7/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/arlan.uy/.local/lib/python3.7/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/home/arlan.uy/.local/lib/python3.7/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/home/arlan.uy/.local/lib/python3.7/site-packages/pip/_internal/configuration.py", line 21, in <module>
    from pip._internal.exceptions import (
  File "/home/arlan.uy/.local/lib/python3.7/site-packages/pip/_internal/exceptions.py", line 8, in <module>
    from pip._vendor.requests.models import Request, Response
  File "/home/arlan.uy/.local/lib/python3.7/site-packages/pip/_vendor/requests/__init__.py", line 136, in <module>
    from . import packages
  File "/home/arlan.uy/.local/lib/python3.7/site-packages/pip/_vendor/requests/packages.py", line 8, in <module>
    locals()[package] = __import__(vendored_package)
  File "/home/arlan.uy/.local/lib/python3.7/site-packages/pip/_vendor/idna/__init__.py", line 2, in <module>
    from .core import (
  File "/home/arlan.uy/.local/lib/python3.7/site-packages/pip/_vendor/idna/core.py", line 3, in <module>
    import unicodedata
ImportError: /opt/hpcc/CPU/anaconda/3-5.3.1/lib/python3.7/lib-dynload/unicodedata.cpython-37m-x86_64-linux-gnu.so: cannot open shared object file: Input/output error
srun: error: saliksik-gpu-05: task 3: Exited with exit code 1
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /home/arlan.uy/.local/include/python3.7m/UNKNOWN
sysconfig: /home/arlan.uy/.local/include/python3.7/UNKNOWN
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /home/arlan.uy/.local/include/python3.7m/UNKNOWN
sysconfig: /home/arlan.uy/.local/include/python3.7/UNKNOWN
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /home/arlan.uy/.local/include/python3.7m/UNKNOWN
sysconfig: /home/arlan.uy/.local/include/python3.7/UNKNOWN
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /home/arlan.uy/.local/include/python3.7m/UNKNOWN
sysconfig: /home/arlan.uy/.local/include/python3.7/UNKNOWN
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /home/arlan.uy/.local/include/python3.7m/UNKNOWN
sysconfig: /home/arlan.uy/.local/include/python3.7/UNKNOWN
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /home/arlan.uy/.local/include/python3.7m/UNKNOWN
sysconfig: /home/arlan.uy/.local/include/python3.7/UNKNOWN
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
distutils: /home/arlan.uy/.local/include/python3.7m/UNKNOWN
sysconfig: /home/arlan.uy/.local/include/python3.7/UNKNOWN
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 188, in program_main
    gaframework(system, test_cases_path, savefile_name)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/experimenter_uncommented.py", line 26, in gaframework
    execute_experiment(rssnp, ga, gaeval, ga_params, loadfile_name, start_new, start_from_gen)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/experimenter_uncommented.py", line 49, in execute_experiment
    gaeval.run(ga, rssnp, stats_run['population_size'], stats_run['fitness_function'],  gaeval.no_of_run, gaeval.no_of_gen, stats_run['mutation_rate'], loadfile_name, stats_run['selection_func'], start_new, start_from_gen)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/GAevaluator_integ.py", line 38, in run
    run_fitness = genetic_algo.simulate(system, size, function, generations, mutation_rate, path_name, run, selection_func, start_from_gen)            
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ.py", line 303, in simulate
    self.evaluate(chrom, function)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ.py", line 253, in evaluate
    chromosome['fitness'] += assign_fitness(chromosome['system'].out_spiketrain, pair['output'], function)/minlen*100
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ.py", line 39, in assign_fitness
    result = lc_subsequence(string_format(generated), string_format(actual))      
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/fitness.py", line 153, in lc_subsequence
    timer_write("Evaluate", start, finish)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/cpu_timer.py", line 29, in timer_write
    timer_params['run_indexes'][run_index_state][ga_name] += finish - start
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 188, in program_main
    gaframework(system, test_cases_path, savefile_name)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/experimenter_uncommented.py", line 26, in gaframework
    execute_experiment(rssnp, ga, gaeval, ga_params, loadfile_name, start_new, start_from_gen)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/experimenter_uncommented.py", line 49, in execute_experiment
    gaeval.run(ga, rssnp, stats_run['population_size'], stats_run['fitness_function'],  gaeval.no_of_run, gaeval.no_of_gen, stats_run['mutation_rate'], loadfile_name, stats_run['selection_func'], start_new, start_from_gen)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/GAevaluator_integ.py", line 38, in run
    run_fitness = genetic_algo.simulate(system, size, function, generations, mutation_rate, path_name, run, selection_func, start_from_gen)            
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ.py", line 303, in simulate
    self.evaluate(chrom, function)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ.py", line 253, in evaluate
    chromosome['fitness'] += assign_fitness(chromosome['system'].out_spiketrain, pair['output'], function)/minlen*100
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ.py", line 39, in assign_fitness
    result = lc_subsequence(string_format(generated), string_format(actual))      
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/fitness.py", line 153, in lc_subsequence
    timer_write("Evaluate", start, finish)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/cpu_timer.py", line 29, in timer_write
    timer_params['run_indexes'][run_index_state][ga_name] += finish - start
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 188, in program_main
    gaframework(system, test_cases_path, savefile_name)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/experimenter_uncommented.py", line 26, in gaframework
    execute_experiment(rssnp, ga, gaeval, ga_params, loadfile_name, start_new, start_from_gen)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/experimenter_uncommented.py", line 49, in execute_experiment
    gaeval.run(ga, rssnp, stats_run['population_size'], stats_run['fitness_function'],  gaeval.no_of_run, gaeval.no_of_gen, stats_run['mutation_rate'], loadfile_name, stats_run['selection_func'], start_new, start_from_gen)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/GAevaluator_integ.py", line 38, in run
    run_fitness = genetic_algo.simulate(system, size, function, generations, mutation_rate, path_name, run, selection_func, start_from_gen)            
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ.py", line 303, in simulate
    self.evaluate(chrom, function)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ.py", line 253, in evaluate
    chromosome['fitness'] += assign_fitness(chromosome['system'].out_spiketrain, pair['output'], function)/minlen*100
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ.py", line 39, in assign_fitness
    result = lc_subsequence(string_format(generated), string_format(actual))      
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/fitness.py", line 153, in lc_subsequence
    timer_write("Evaluate", start, finish)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/cpu_timer.py", line 29, in timer_write
    timer_params['run_indexes'][run_index_state][ga_name] += finish - start
TypeError: 'NoneType' object is not subscriptable
srun: error: saliksik-gpu-05: tasks 6-7: Exited with exit code 1
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 188, in program_main
    gaframework(system, test_cases_path, savefile_name)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/experimenter_uncommented.py", line 26, in gaframework
    execute_experiment(rssnp, ga, gaeval, ga_params, loadfile_name, start_new, start_from_gen)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/experimenter_uncommented.py", line 49, in execute_experiment
    gaeval.run(ga, rssnp, stats_run['population_size'], stats_run['fitness_function'],  gaeval.no_of_run, gaeval.no_of_gen, stats_run['mutation_rate'], loadfile_name, stats_run['selection_func'], start_new, start_from_gen)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/GAevaluator_integ.py", line 38, in run
    run_fitness = genetic_algo.simulate(system, size, function, generations, mutation_rate, path_name, run, selection_func, start_from_gen)            
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ.py", line 303, in simulate
    self.evaluate(chrom, function)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ.py", line 253, in evaluate
    chromosome['fitness'] += assign_fitness(chromosome['system'].out_spiketrain, pair['output'], function)/minlen*100
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ.py", line 39, in assign_fitness
    result = lc_subsequence(string_format(generated), string_format(actual))      
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/fitness.py", line 153, in lc_subsequence
    timer_write("Evaluate", start, finish)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/cpu_timer.py", line 29, in timer_write
    timer_params['run_indexes'][run_index_state][ga_name] += finish - start
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 188, in program_main
    gaframework(system, test_cases_path, savefile_name)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/experimenter_uncommented.py", line 26, in gaframework
    execute_experiment(rssnp, ga, gaeval, ga_params, loadfile_name, start_new, start_from_gen)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/experimenter_uncommented.py", line 49, in execute_experiment
    gaeval.run(ga, rssnp, stats_run['population_size'], stats_run['fitness_function'],  gaeval.no_of_run, gaeval.no_of_gen, stats_run['mutation_rate'], loadfile_name, stats_run['selection_func'], start_new, start_from_gen)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/GAevaluator_integ.py", line 38, in run
    run_fitness = genetic_algo.simulate(system, size, function, generations, mutation_rate, path_name, run, selection_func, start_from_gen)            
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ.py", line 303, in simulate
    self.evaluate(chrom, function)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ.py", line 253, in evaluate
    chromosome['fitness'] += assign_fitness(chromosome['system'].out_spiketrain, pair['output'], function)/minlen*100
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ.py", line 39, in assign_fitness
    result = lc_subsequence(string_format(generated), string_format(actual))      
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/fitness.py", line 153, in lc_subsequence
    timer_write("Evaluate", start, finish)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/cpu_timer.py", line 29, in timer_write
    timer_params['run_indexes'][run_index_state][ga_name] += finish - start
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 188, in program_main
    gaframework(system, test_cases_path, savefile_name)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/experimenter_uncommented.py", line 26, in gaframework
    execute_experiment(rssnp, ga, gaeval, ga_params, loadfile_name, start_new, start_from_gen)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/experimenter_uncommented.py", line 49, in execute_experiment
    gaeval.run(ga, rssnp, stats_run['population_size'], stats_run['fitness_function'],  gaeval.no_of_run, gaeval.no_of_gen, stats_run['mutation_rate'], loadfile_name, stats_run['selection_func'], start_new, start_from_gen)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/GAevaluator_integ.py", line 38, in run
    run_fitness = genetic_algo.simulate(system, size, function, generations, mutation_rate, path_name, run, selection_func, start_from_gen)            
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ.py", line 303, in simulate
    self.evaluate(chrom, function)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ.py", line 253, in evaluate
    chromosome['fitness'] += assign_fitness(chromosome['system'].out_spiketrain, pair['output'], function)/minlen*100
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ.py", line 39, in assign_fitness
    result = lc_subsequence(string_format(generated), string_format(actual))      
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/fitness.py", line 153, in lc_subsequence
    timer_write("Evaluate", start, finish)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/cpu_timer.py", line 29, in timer_write
    timer_params['run_indexes'][run_index_state][ga_name] += finish - start
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 188, in program_main
    gaframework(system, test_cases_path, savefile_name)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/experimenter_uncommented.py", line 26, in gaframework
    execute_experiment(rssnp, ga, gaeval, ga_params, loadfile_name, start_new, start_from_gen)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/experimenter_uncommented.py", line 49, in execute_experiment
    gaeval.run(ga, rssnp, stats_run['population_size'], stats_run['fitness_function'],  gaeval.no_of_run, gaeval.no_of_gen, stats_run['mutation_rate'], loadfile_name, stats_run['selection_func'], start_new, start_from_gen)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/GAevaluator_integ.py", line 38, in run
    run_fitness = genetic_algo.simulate(system, size, function, generations, mutation_rate, path_name, run, selection_func, start_from_gen)            
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ.py", line 303, in simulate
    self.evaluate(chrom, function)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ.py", line 253, in evaluate
    chromosome['fitness'] += assign_fitness(chromosome['system'].out_spiketrain, pair['output'], function)/minlen*100
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ.py", line 39, in assign_fitness
    result = lc_subsequence(string_format(generated), string_format(actual))      
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/fitness.py", line 153, in lc_subsequence
    timer_write("Evaluate", start, finish)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/cpu_timer.py", line 29, in timer_write
    timer_params['run_indexes'][run_index_state][ga_name] += finish - start
TypeError: 'NoneType' object is not subscriptable
srun: error: saliksik-gpu-05: tasks 0-2,4-5: Exited with exit code 1
