>> anaconda-3-5.3.1 has been loaded.
>> python-3.9.7 has been loaded.
>> cuda-10.1_cudnn-7.6.5 has been loaded.
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 276, in program_main
    continue_create_empty_yaml(newloadfile_name)
  File "main.py", line 42, in continue_create_empty_yaml
    for i in range(run_start, ga_params['run_total'] + ga_params['runs_pending']):
KeyError: 'runs_pending'
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 276, in program_main
    continue_create_empty_yaml(newloadfile_name)
  File "main.py", line 42, in continue_create_empty_yaml
    for i in range(run_start, ga_params['run_total'] + ga_params['runs_pending']):
KeyError: 'runs_pending'
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 276, in program_main
    continue_create_empty_yaml(newloadfile_name)
  File "main.py", line 42, in continue_create_empty_yaml
    for i in range(run_start, ga_params['run_total'] + ga_params['runs_pending']):
KeyError: 'runs_pending'
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 276, in program_main
    continue_create_empty_yaml(newloadfile_name)
  File "main.py", line 42, in continue_create_empty_yaml
    for i in range(run_start, ga_params['run_total'] + ga_params['runs_pending']):
KeyError: 'runs_pending'
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 276, in program_main
    continue_create_empty_yaml(newloadfile_name)
  File "main.py", line 42, in continue_create_empty_yaml
    for i in range(run_start, ga_params['run_total'] + ga_params['runs_pending']):
KeyError: 'runs_pending'
srun: error: saliksik-gpu-05: tasks 1,5: Exited with exit code 1
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 276, in program_main
    continue_create_empty_yaml(newloadfile_name)
  File "main.py", line 42, in continue_create_empty_yaml
    for i in range(run_start, ga_params['run_total'] + ga_params['runs_pending']):
KeyError: 'runs_pending'
srun: error: saliksik-gpu-05: tasks 0,6,8,10: Exited with exit code 1
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 278, in program_main
    run_total = ga_params['run_total'] + ga_params['runs_pending']
KeyError: 'runs_pending'
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 278, in program_main
    run_total = ga_params['run_total'] + ga_params['runs_pending']
KeyError: 'runs_pending'
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 278, in program_main
    run_total = ga_params['run_total'] + ga_params['runs_pending']
KeyError: 'runs_pending'
srun: error: saliksik-gpu-05: tasks 3,11: Exited with exit code 1
srun: error: saliksik-gpu-05: task 7: Exited with exit code 1
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 288, in program_main
    gaframework_gpu(newloadfile_name)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/experimenter_uncommented.py", line 34, in gaframework_gpu
    execute_experiment_gpu(ga, gaeval, ga_params, loadfile_name)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/experimenter_uncommented.py", line 63, in execute_experiment_gpu
    gaeval.run(ga, rssnp, stats_run['population_size'], stats_run['fitness_function'],  gaeval.no_of_run, gaeval.no_of_gen, stats_run['mutation_rate'], loadfile_name, stats_run['selection_func'], start_new, start_from_gen)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/GAevaluator_integ.py", line 38, in run
    run_fitness = genetic_algo.simulate(system, size, function, generations, mutation_rate, path_name, run, selection_func, start_from_gen)            
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ_gpu.py", line 414, in simulate
    self.use_population(ga_params['runs'][run_start]['population_size'], ga_params['runs'][run_start]['generations'][generation_start]['rssnp_chromosomes'] )
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ_gpu.py", line 393, in use_population
    system = assign_rssnp(last_gen_chromosomes[chromosome])
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/rssnp.py", line 551, in assign_rssnp
    system.n = rssnp['neurons']    # number of neurons
KeyError: 'neurons'
srun: error: saliksik-gpu-05: task 9: Exited with exit code 1
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 288, in program_main
    gaframework_gpu(newloadfile_name)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/experimenter_uncommented.py", line 34, in gaframework_gpu
    execute_experiment_gpu(ga, gaeval, ga_params, loadfile_name)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/experimenter_uncommented.py", line 63, in execute_experiment_gpu
    gaeval.run(ga, rssnp, stats_run['population_size'], stats_run['fitness_function'],  gaeval.no_of_run, gaeval.no_of_gen, stats_run['mutation_rate'], loadfile_name, stats_run['selection_func'], start_new, start_from_gen)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/GAevaluator_integ.py", line 38, in run
    run_fitness = genetic_algo.simulate(system, size, function, generations, mutation_rate, path_name, run, selection_func, start_from_gen)            
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ_gpu.py", line 414, in simulate
    self.use_population(ga_params['runs'][run_start]['population_size'], ga_params['runs'][run_start]['generations'][generation_start]['rssnp_chromosomes'] )
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ_gpu.py", line 393, in use_population
    system = assign_rssnp(last_gen_chromosomes[chromosome])
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/rssnp.py", line 551, in assign_rssnp
    system.n = rssnp['neurons']    # number of neurons
KeyError: 'neurons'
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 288, in program_main
    gaframework_gpu(newloadfile_name)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/experimenter_uncommented.py", line 34, in gaframework_gpu
    execute_experiment_gpu(ga, gaeval, ga_params, loadfile_name)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/experimenter_uncommented.py", line 63, in execute_experiment_gpu
    gaeval.run(ga, rssnp, stats_run['population_size'], stats_run['fitness_function'],  gaeval.no_of_run, gaeval.no_of_gen, stats_run['mutation_rate'], loadfile_name, stats_run['selection_func'], start_new, start_from_gen)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/GAevaluator_integ.py", line 38, in run
    run_fitness = genetic_algo.simulate(system, size, function, generations, mutation_rate, path_name, run, selection_func, start_from_gen)            
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ_gpu.py", line 414, in simulate
    self.use_population(ga_params['runs'][run_start]['population_size'], ga_params['runs'][run_start]['generations'][generation_start]['rssnp_chromosomes'] )
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ_gpu.py", line 393, in use_population
    system = assign_rssnp(last_gen_chromosomes[chromosome])
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/rssnp.py", line 551, in assign_rssnp
    system.n = rssnp['neurons']    # number of neurons
KeyError: 'neurons'
srun: error: saliksik-gpu-05: task 2: Exited with exit code 1
srun: error: saliksik-gpu-05: task 4: Exited with exit code 1
