>> anaconda-3-5.3.1 has been loaded.
>> python-3.9.7 has been loaded.
>> cuda-10.1_cudnn-7.6.5 has been loaded.
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 276, in program_main
    continue_create_empty_yaml(newloadfile_name)
  File "main.py", line 42, in continue_create_empty_yaml
    for i in range(run_start, ga_params['run_total'] + ga_params['runs_pending']):
KeyError: 'runs_pending'
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 276, in program_main
    continue_create_empty_yaml(newloadfile_name)
  File "main.py", line 42, in continue_create_empty_yaml
    for i in range(run_start, ga_params['run_total'] + ga_params['runs_pending']):
KeyError: 'runs_pending'
srun: error: saliksik-gpu-06: task 5: Exited with exit code 1
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 276, in program_main
    continue_create_empty_yaml(newloadfile_name)
  File "main.py", line 42, in continue_create_empty_yaml
    for i in range(run_start, ga_params['run_total'] + ga_params['runs_pending']):
KeyError: 'runs_pending'
srun: error: saliksik-gpu-06: tasks 1,8: Exited with exit code 1
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 276, in program_main
    continue_create_empty_yaml(newloadfile_name)
  File "main.py", line 42, in continue_create_empty_yaml
    for i in range(run_start, ga_params['run_total'] + ga_params['runs_pending']):
KeyError: 'runs_pending'
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 276, in program_main
    continue_create_empty_yaml(newloadfile_name)
  File "main.py", line 42, in continue_create_empty_yaml
    for i in range(run_start, ga_params['run_total'] + ga_params['runs_pending']):
KeyError: 'runs_pending'
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 276, in program_main
    continue_create_empty_yaml(newloadfile_name)
  File "main.py", line 42, in continue_create_empty_yaml
    for i in range(run_start, ga_params['run_total'] + ga_params['runs_pending']):
KeyError: 'runs_pending'
srun: error: saliksik-gpu-06: task 6: Exited with exit code 1
srun: error: saliksik-gpu-06: task 9: Exited with exit code 1
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 276, in program_main
    continue_create_empty_yaml(newloadfile_name)
  File "main.py", line 42, in continue_create_empty_yaml
    for i in range(run_start, ga_params['run_total'] + ga_params['runs_pending']):
KeyError: 'runs_pending'
srun: error: saliksik-gpu-06: task 7: Exited with exit code 1
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 276, in program_main
    continue_create_empty_yaml(newloadfile_name)
  File "main.py", line 42, in continue_create_empty_yaml
    for i in range(run_start, ga_params['run_total'] + ga_params['runs_pending']):
KeyError: 'runs_pending'
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 276, in program_main
    continue_create_empty_yaml(newloadfile_name)
  File "main.py", line 42, in continue_create_empty_yaml
    for i in range(run_start, ga_params['run_total'] + ga_params['runs_pending']):
KeyError: 'runs_pending'
srun: error: saliksik-gpu-06: task 2: Exited with exit code 1
srun: error: saliksik-gpu-06: tasks 0,3: Exited with exit code 1
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 278, in program_main
    run_total = ga_params['run_total'] + ga_params['runs_pending']
KeyError: 'runs_pending'
srun: error: saliksik-gpu-06: task 10: Exited with exit code 1
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 278, in program_main
    run_total = ga_params['run_total'] + ga_params['runs_pending']
KeyError: 'runs_pending'
srun: error: saliksik-gpu-06: task 4: Exited with exit code 1
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuModuleUnload failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuModuleUnload failed: an illegal memory access was encountered
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 288, in program_main
    gaframework_gpu(newloadfile_name)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/experimenter_uncommented.py", line 34, in gaframework_gpu
    execute_experiment_gpu(ga, gaeval, ga_params, loadfile_name)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/experimenter_uncommented.py", line 63, in execute_experiment_gpu
    gaeval.run(ga, rssnp, stats_run['population_size'], stats_run['fitness_function'],  gaeval.no_of_run, gaeval.no_of_gen, stats_run['mutation_rate'], loadfile_name, stats_run['selection_func'], start_new, start_from_gen)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/GAevaluator_integ.py", line 38, in run
    run_fitness = genetic_algo.simulate(system, size, function, generations, mutation_rate, path_name, run, selection_func, start_from_gen)            
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ_gpu.py", line 469, in simulate
    self.crossover(mutation_rate, selection_func)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/geneticalgo_integ_gpu.py", line 176, in crossover
    crossover_indexes = crossover_gpu_defined(len(parents), len_orig_parents, num_crosses, self.pop, random_rule_parents_limit)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/gpu_crossover.py", line 28, in crossover_gpu_defined
    random_fin_list = getrandom(parents_size, num_crosses, np.random.randint(123456789), random_rule_parents_limit)
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/getrandomnums.py", line 70, in getrandom
    timer_gpu.toc()
  File "/scratch1/scratch2/arlan.uy/ERSSNP_CPU_GPU_Framework/main_dir/src/abstracts/gpu_timer.py", line 58, in toc
    self.end.synchronize()
pycuda._driver.LogicError: cuEventSynchronize failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuModuleUnload failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuEventDestroy failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuEventDestroy failed: an illegal memory access was encountered
srun: error: saliksik-gpu-06: task 11: Exited with exit code 1
