WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
WARNING: Skipping page https://pypi.org/simple/attrs/ because the GET request got Content-Type: .The only supported Content-Type is text/html
ERROR: Could not find a version that satisfies the requirement attrs==18.2.0 (from versions: none)
ERROR: No matching distribution found for attrs==18.2.0
WARNING: Skipping page https://pypi.org/simple/attrs/ because the GET request got Content-Type: .The only supported Content-Type is text/html
ERROR: Could not find a version that satisfies the requirement attrs==18.2.0 (from versions: none)
ERROR: No matching distribution found for attrs==18.2.0
srun: error: saliksik-gpu-06: tasks 2,6: Exited with exit code 1
    ERROR: Command errored out with exit status 1:
     command: /opt/hpcc/CPU/python/3.8.2/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-53m6qbyv/greenery_38d38181f8a14847a393f33abda5e49c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-53m6qbyv/greenery_38d38181f8a14847a393f33abda5e49c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-p0aap4rd
         cwd: /tmp/pip-install-53m6qbyv/greenery_38d38181f8a14847a393f33abda5e49c/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/hpcc/CPU/python/3.8.2/lib/python3.8/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/opt/hpcc/CPU/python/3.8.2/lib/python3.8/site-packages/setuptools/dist.py", line 35, in <module>
        from setuptools import windows_support
      File "/opt/hpcc/CPU/python/3.8.2/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/opt/hpcc/CPU/python/3.8.2/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
    ERROR: Command errored out with exit status 1:
     command: /opt/hpcc/CPU/python/3.8.2/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j4bj4ric/greenery_40e10be4e2ff4923b5ec48d8b8371f48/setup.py'"'"'; __file__='"'"'/tmp/pip-install-j4bj4ric/greenery_40e10be4e2ff4923b5ec48d8b8371f48/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-b4rvgklu
         cwd: /tmp/pip-install-j4bj4ric/greenery_40e10be4e2ff4923b5ec48d8b8371f48/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/hpcc/CPU/python/3.8.2/lib/python3.8/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/opt/hpcc/CPU/python/3.8.2/lib/python3.8/site-packages/setuptools/dist.py", line 35, in <module>
        from setuptools import windows_support
      File "/opt/hpcc/CPU/python/3.8.2/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/opt/hpcc/CPU/python/3.8.2/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/82/69/2c2a77e7034650954e54144ea2b88ec8742a81ac69fbe84da319e0e9112c/greenery-3.1.zip#sha256=e2d98192187bc27caa218ae59d5e34a779ec538ecd3ec839c469f36686421a7e (from https://pypi.org/simple/greenery/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: Discarding https://files.pythonhosted.org/packages/82/69/2c2a77e7034650954e54144ea2b88ec8742a81ac69fbe84da319e0e9112c/greenery-3.1.zip#sha256=e2d98192187bc27caa218ae59d5e34a779ec538ecd3ec839c469f36686421a7e (from https://pypi.org/simple/greenery/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement greenery==3.1 (from versions: 1.0, 1.1, 2.0, 2.1, 3.0, 3.1, 3.2, 3.3.1, 3.3.2)
ERROR: No matching distribution found for greenery==3.1
ERROR: Could not find a version that satisfies the requirement greenery==3.1 (from versions: 1.0, 1.1, 2.0, 2.1, 3.0, 3.1, 3.2, 3.3.1, 3.3.2)
ERROR: No matching distribution found for greenery==3.1
    ERROR: Command errored out with exit status 1:
     command: /opt/hpcc/CPU/python/3.8.2/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yqhs_sw_/greenery_2cdfabf3f8644e87b7f2a49f34a7724b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yqhs_sw_/greenery_2cdfabf3f8644e87b7f2a49f34a7724b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-hwfclxg7
         cwd: /tmp/pip-install-yqhs_sw_/greenery_2cdfabf3f8644e87b7f2a49f34a7724b/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/hpcc/CPU/python/3.8.2/lib/python3.8/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/opt/hpcc/CPU/python/3.8.2/lib/python3.8/site-packages/setuptools/dist.py", line 35, in <module>
        from setuptools import windows_support
      File "/opt/hpcc/CPU/python/3.8.2/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/opt/hpcc/CPU/python/3.8.2/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/82/69/2c2a77e7034650954e54144ea2b88ec8742a81ac69fbe84da319e0e9112c/greenery-3.1.zip#sha256=e2d98192187bc27caa218ae59d5e34a779ec538ecd3ec839c469f36686421a7e (from https://pypi.org/simple/greenery/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: /opt/hpcc/CPU/python/3.8.2/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dt7_j3iq/greenery_36e7ffea4c124b0eb3de11df7faca02a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dt7_j3iq/greenery_36e7ffea4c124b0eb3de11df7faca02a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-pv2wxm1l
         cwd: /tmp/pip-install-dt7_j3iq/greenery_36e7ffea4c124b0eb3de11df7faca02a/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/hpcc/CPU/python/3.8.2/lib/python3.8/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/opt/hpcc/CPU/python/3.8.2/lib/python3.8/site-packages/setuptools/dist.py", line 35, in <module>
        from setuptools import windows_support
      File "/opt/hpcc/CPU/python/3.8.2/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/opt/hpcc/CPU/python/3.8.2/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
    ERROR: Command errored out with exit status 1:
     command: /opt/hpcc/CPU/python/3.8.2/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_gq5i0zi/greenery_3e79c9f91a4d4ec884eabc08bf111bbb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_gq5i0zi/greenery_3e79c9f91a4d4ec884eabc08bf111bbb/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-k3e3i7fe
         cwd: /tmp/pip-install-_gq5i0zi/greenery_3e79c9f91a4d4ec884eabc08bf111bbb/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/hpcc/CPU/python/3.8.2/lib/python3.8/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/opt/hpcc/CPU/python/3.8.2/lib/python3.8/site-packages/setuptools/dist.py", line 35, in <module>
        from setuptools import windows_support
      File "/opt/hpcc/CPU/python/3.8.2/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/opt/hpcc/CPU/python/3.8.2/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
    ERROR: Command errored out with exit status 1:
     command: /opt/hpcc/CPU/python/3.8.2/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uy60ovxs/greenery_2b1c8967b6a64215a476be0465d56283/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uy60ovxs/greenery_2b1c8967b6a64215a476be0465d56283/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-fk7ri3hf
         cwd: /tmp/pip-install-uy60ovxs/greenery_2b1c8967b6a64215a476be0465d56283/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/hpcc/CPU/python/3.8.2/lib/python3.8/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/opt/hpcc/CPU/python/3.8.2/lib/python3.8/site-packages/setuptools/dist.py", line 35, in <module>
        from setuptools import windows_support
      File "/opt/hpcc/CPU/python/3.8.2/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/opt/hpcc/CPU/python/3.8.2/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
ERROR: Could not find a version that satisfies the requirement greenery==3.1 (from versions: 1.0, 1.1, 2.0, 2.1, 3.0, 3.1, 3.2, 3.3.1, 3.3.2)
ERROR: No matching distribution found for greenery==3.1
WARNING: Discarding https://files.pythonhosted.org/packages/82/69/2c2a77e7034650954e54144ea2b88ec8742a81ac69fbe84da319e0e9112c/greenery-3.1.zip#sha256=e2d98192187bc27caa218ae59d5e34a779ec538ecd3ec839c469f36686421a7e (from https://pypi.org/simple/greenery/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: Discarding https://files.pythonhosted.org/packages/82/69/2c2a77e7034650954e54144ea2b88ec8742a81ac69fbe84da319e0e9112c/greenery-3.1.zip#sha256=e2d98192187bc27caa218ae59d5e34a779ec538ecd3ec839c469f36686421a7e (from https://pypi.org/simple/greenery/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: Discarding https://files.pythonhosted.org/packages/82/69/2c2a77e7034650954e54144ea2b88ec8742a81ac69fbe84da319e0e9112c/greenery-3.1.zip#sha256=e2d98192187bc27caa218ae59d5e34a779ec538ecd3ec839c469f36686421a7e (from https://pypi.org/simple/greenery/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement greenery==3.1 (from versions: 1.0, 1.1, 2.0, 2.1, 3.0, 3.1, 3.2, 3.3.1, 3.3.2)
ERROR: Could not find a version that satisfies the requirement greenery==3.1 (from versions: 1.0, 1.1, 2.0, 2.1, 3.0, 3.1, 3.2, 3.3.1, 3.3.2)
ERROR: Could not find a version that satisfies the requirement greenery==3.1 (from versions: 1.0, 1.1, 2.0, 2.1, 3.0, 3.1, 3.2, 3.3.1, 3.3.2)
ERROR: No matching distribution found for greenery==3.1
ERROR: No matching distribution found for greenery==3.1
ERROR: No matching distribution found for greenery==3.1
srun: error: saliksik-gpu-06: tasks 3,7: Exited with exit code 1
srun: error: saliksik-gpu-06: tasks 0-1,4-5: Exited with exit code 1
Traceback (most recent call last):
  File "src/abstracts/gpu_selection.py", line 1, in <module>
    import pycuda.autoinit
ModuleNotFoundError: No module named 'pycuda'
Traceback (most recent call last):
  File "src/abstracts/gpu_selection.py", line 1, in <module>
    import pycuda.autoinit
ModuleNotFoundError: No module named 'pycuda'
Traceback (most recent call last):
  File "src/abstracts/gpu_selection.py", line 1, in <module>
    import pycuda.autoinit
ModuleNotFoundError: No module named 'pycuda'
Traceback (most recent call last):
  File "src/abstracts/gpu_selection.py", line 1, in <module>
    import pycuda.autoinit
ModuleNotFoundError: No module named 'pycuda'
Traceback (most recent call last):
  File "src/abstracts/gpu_selection.py", line 1, in <module>
    import pycuda.autoinit
ModuleNotFoundError: No module named 'pycuda'
Traceback (most recent call last):
  File "src/abstracts/gpu_selection.py", line 1, in <module>
    import pycuda.autoinit
ModuleNotFoundError: No module named 'pycuda'
Traceback (most recent call last):
  File "src/abstracts/gpu_selection.py", line 1, in <module>
    import pycuda.autoinit
ModuleNotFoundError: No module named 'pycuda'
Traceback (most recent call last):
  File "src/abstracts/gpu_selection.py", line 1, in <module>
    import pycuda.autoinit
ModuleNotFoundError: No module named 'pycuda'
srun: error: saliksik-gpu-06: tasks 0-7: Exited with exit code 1
